package mx.com.cdc.odc.client.model;

import java.util.Objects;

import org.threeten.bp.LocalDate;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;


public class EnergyRequestPayload {
  @SerializedName("request_code")
  private String requestCode = null;
  @SerializedName("start_date")
  private LocalDate startDate = null;
  @SerializedName("read_customer")
  private Boolean readCustomer = null;
  @SerializedName("read_account_details")
  private Boolean readAccountDetails = null;
  public EnergyRequestPayload requestCode(String requestCode) {
    this.requestCode = requestCode;
    return this;
  }
   
  @ApiModelProperty(value = "Unique alphanumeric identifier for the request. This must be generated by the merchant. Max: 36 characters")
  public String getRequestCode() {
    return requestCode;
  }
  public void setRequestCode(String requestCode) {
    this.requestCode = requestCode;
  }
  public EnergyRequestPayload startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public LocalDate getStartDate() {
    return startDate;
  }
  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }
  public EnergyRequestPayload readCustomer(Boolean readCustomer) {
    this.readCustomer = readCustomer;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true brings the details of the customers available.")
  public Boolean isReadCustomer() {
    return readCustomer;
  }
  public void setReadCustomer(Boolean readCustomer) {
    this.readCustomer = readCustomer;
  }
  public EnergyRequestPayload readAccountDetails(Boolean readAccountDetails) {
    this.readAccountDetails = readAccountDetails;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true brings the details of the service account.")
  public Boolean isReadAccountDetails() {
    return readAccountDetails;
  }
  public void setReadAccountDetails(Boolean readAccountDetails) {
    this.readAccountDetails = readAccountDetails;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnergyRequestPayload energyRequestPayload = (EnergyRequestPayload) o;
    return Objects.equals(this.requestCode, energyRequestPayload.requestCode) &&
        Objects.equals(this.startDate, energyRequestPayload.startDate) &&
        Objects.equals(this.readCustomer, energyRequestPayload.readCustomer) &&
        Objects.equals(this.readAccountDetails, energyRequestPayload.readAccountDetails);
  }
  @Override
  public int hashCode() {
    return Objects.hash(requestCode, startDate, readCustomer, readAccountDetails);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnergyRequestPayload {\n");
    
    sb.append("    requestCode: ").append(toIndentedString(requestCode)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    readCustomer: ").append(toIndentedString(readCustomer)).append("\n");
    sb.append("    readAccountDetails: ").append(toIndentedString(readAccountDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
