package mx.com.cdc.odc.client.model;

import java.util.Objects;

import org.threeten.bp.LocalDate;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;


public class RetailRequestPayload {
  @SerializedName("request_code")
  private String requestCode = null;
  @SerializedName("start_date")
  private LocalDate startDate = null;
  @SerializedName("read_shopping")
  private Boolean readShopping = null;
  @SerializedName("read_shopping_credits")
  private Boolean readShoppingCredits = null;
  @SerializedName("read_shopping_credit_billing")
  private Boolean readShoppingCreditBilling = null;
  public RetailRequestPayload requestCode(String requestCode) {
    this.requestCode = requestCode;
    return this;
  }
   
  @ApiModelProperty(value = "Unique alphanumeric identifier for the request. This must be generated by the merchant. Max: 36 characters")
  public String getRequestCode() {
    return requestCode;
  }
  public void setRequestCode(String requestCode) {
    this.requestCode = requestCode;
  }
  public RetailRequestPayload startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public LocalDate getStartDate() {
    return startDate;
  }
  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }
  public RetailRequestPayload readShopping(Boolean readShopping) {
    this.readShopping = readShopping;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true and if available, brings back the information of items bought in the retail store.")
  public Boolean isReadShopping() {
    return readShopping;
  }
  public void setReadShopping(Boolean readShopping) {
    this.readShopping = readShopping;
  }
  public RetailRequestPayload readShoppingCredits(Boolean readShoppingCredits) {
    this.readShoppingCredits = readShoppingCredits;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true will show information related to credit or loans that the customer may have in the retails store.")
  public Boolean isReadShoppingCredits() {
    return readShoppingCredits;
  }
  public void setReadShoppingCredits(Boolean readShoppingCredits) {
    this.readShoppingCredits = readShoppingCredits;
  }
  public RetailRequestPayload readShoppingCreditBilling(Boolean readShoppingCreditBilling) {
    this.readShoppingCreditBilling = readShoppingCreditBilling;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true will request the information related to the statements linked to the credits or loans available.")
  public Boolean isReadShoppingCreditBilling() {
    return readShoppingCreditBilling;
  }
  public void setReadShoppingCreditBilling(Boolean readShoppingCreditBilling) {
    this.readShoppingCreditBilling = readShoppingCreditBilling;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetailRequestPayload retailRequestPayload = (RetailRequestPayload) o;
    return Objects.equals(this.requestCode, retailRequestPayload.requestCode) &&
        Objects.equals(this.startDate, retailRequestPayload.startDate) &&
        Objects.equals(this.readShopping, retailRequestPayload.readShopping) &&
        Objects.equals(this.readShoppingCredits, retailRequestPayload.readShoppingCredits) &&
        Objects.equals(this.readShoppingCreditBilling, retailRequestPayload.readShoppingCreditBilling);
  }
  @Override
  public int hashCode() {
    return Objects.hash(requestCode, startDate, readShopping, readShoppingCredits, readShoppingCreditBilling);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetailRequestPayload {\n");
    
    sb.append("    requestCode: ").append(toIndentedString(requestCode)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    readShopping: ").append(toIndentedString(readShopping)).append("\n");
    sb.append("    readShoppingCredits: ").append(toIndentedString(readShoppingCredits)).append("\n");
    sb.append("    readShoppingCreditBilling: ").append(toIndentedString(readShoppingCreditBilling)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
