package mx.com.cdc.odc.client.model;

import java.util.Objects;

import org.threeten.bp.LocalDate;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;


public class TelcosRequestPayload {
  @SerializedName("request_code")
  private String requestCode = null;
  @SerializedName("start_date")
  private LocalDate startDate = null;
  @SerializedName("read_summary")
  private Boolean readSummary = null;
  @SerializedName("read_billing")
  private Boolean readBilling = null;
  @SerializedName("read_payment_history")
  private Boolean readPaymentHistory = null;
  @SerializedName("read_plan_details")
  private Boolean readPlanDetails = null;
  @SerializedName("read_credit_payments")
  private Boolean readCreditPayments = null;
  public TelcosRequestPayload requestCode(String requestCode) {
    this.requestCode = requestCode;
    return this;
  }
   
  @ApiModelProperty(value = "Unique alphanumeric identifier for the request. This must be generated by the merchant. Max: 36 characters")
  public String getRequestCode() {
    return requestCode;
  }
  public void setRequestCode(String requestCode) {
    this.requestCode = requestCode;
  }
  public TelcosRequestPayload startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public LocalDate getStartDate() {
    return startDate;
  }
  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }
  public TelcosRequestPayload readSummary(Boolean readSummary) {
    this.readSummary = readSummary;
    return this;
  }
   
  @ApiModelProperty(value = "Brings a summary of the Telco account you are requesting.")
  public Boolean isReadSummary() {
    return readSummary;
  }
  public void setReadSummary(Boolean readSummary) {
    this.readSummary = readSummary;
  }
  public TelcosRequestPayload readBilling(Boolean readBilling) {
    this.readBilling = readBilling;
    return this;
  }
   
  @ApiModelProperty(value = "Brings a detail of the statements available for the account.")
  public Boolean isReadBilling() {
    return readBilling;
  }
  public void setReadBilling(Boolean readBilling) {
    this.readBilling = readBilling;
  }
  public TelcosRequestPayload readPaymentHistory(Boolean readPaymentHistory) {
    this.readPaymentHistory = readPaymentHistory;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true the information about payments performed on the account will be retrieved.")
  public Boolean isReadPaymentHistory() {
    return readPaymentHistory;
  }
  public void setReadPaymentHistory(Boolean readPaymentHistory) {
    this.readPaymentHistory = readPaymentHistory;
  }
  public TelcosRequestPayload readPlanDetails(Boolean readPlanDetails) {
    this.readPlanDetails = readPlanDetails;
    return this;
  }
   
  @ApiModelProperty(value = "When set to true, the information related to the details of the hired plan will be retrieved.")
  public Boolean isReadPlanDetails() {
    return readPlanDetails;
  }
  public void setReadPlanDetails(Boolean readPlanDetails) {
    this.readPlanDetails = readPlanDetails;
  }
  public TelcosRequestPayload readCreditPayments(Boolean readCreditPayments) {
    this.readCreditPayments = readCreditPayments;
    return this;
  }
   
  @ApiModelProperty(value = "When available, the information of credits sent from the read account to other accounts will be collected.")
  public Boolean isReadCreditPayments() {
    return readCreditPayments;
  }
  public void setReadCreditPayments(Boolean readCreditPayments) {
    this.readCreditPayments = readCreditPayments;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TelcosRequestPayload telcosRequestPayload = (TelcosRequestPayload) o;
    return Objects.equals(this.requestCode, telcosRequestPayload.requestCode) &&
        Objects.equals(this.startDate, telcosRequestPayload.startDate) &&
        Objects.equals(this.readSummary, telcosRequestPayload.readSummary) &&
        Objects.equals(this.readBilling, telcosRequestPayload.readBilling) &&
        Objects.equals(this.readPaymentHistory, telcosRequestPayload.readPaymentHistory) &&
        Objects.equals(this.readPlanDetails, telcosRequestPayload.readPlanDetails) &&
        Objects.equals(this.readCreditPayments, telcosRequestPayload.readCreditPayments);
  }
  @Override
  public int hashCode() {
    return Objects.hash(requestCode, startDate, readSummary, readBilling, readPaymentHistory, readPlanDetails, readCreditPayments);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TelcosRequestPayload {\n");
    
    sb.append("    requestCode: ").append(toIndentedString(requestCode)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    readSummary: ").append(toIndentedString(readSummary)).append("\n");
    sb.append("    readBilling: ").append(toIndentedString(readBilling)).append("\n");
    sb.append("    readPaymentHistory: ").append(toIndentedString(readPaymentHistory)).append("\n");
    sb.append("    readPlanDetails: ").append(toIndentedString(readPlanDetails)).append("\n");
    sb.append("    readCreditPayments: ").append(toIndentedString(readCreditPayments)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
